<?php ob_start(); require_once('header.php'); ?>

<?php

ensureBirthdayTables($pdo);

$success_message = '';
$error_message = '';

/*
|--------------------------------------------------------------------------
| HELPER: CREATE IMAGE FILENAME
|--------------------------------------------------------------------------
|
| Example:
| Rumi + 5 = rumi_5.jpg
| Rumi Shrestha + 5 = rumi_shrestha_5.jpg
|
*/
function createBirthdayImageName($studentName, $className, $extension = 'jpg')
{
    $studentName = strtolower(trim($studentName));
    $className   = strtolower(trim($className));

    // Remove "class" from class name if present.
    // Example: Class 5 -> 5
    $className = preg_replace('/^class[\s_-]*/i', '', $className);

    // Convert spaces and special characters to underscore.
    $studentName = preg_replace('/[^a-z0-9]+/i', '_', $studentName);
    $className   = preg_replace('/[^a-z0-9]+/i', '_', $className);

    $studentName = trim($studentName, '_');
    $className   = trim($className, '_');

    $extension = strtolower($extension);
    if (!in_array($extension, ['jpg', 'jpeg', 'png', 'gif', 'webp'], true)) {
        $extension = 'jpg';
    }

    return $studentName . '_' . $className . '.' . $extension;
}

/*
|--------------------------------------------------------------------------
| HELPER: NORMALIZE IMAGE KEY
|--------------------------------------------------------------------------
|
| Rumi_5.jpg
| rumi_5.JPG
|
| Both become:
| rumi_5
|
*/
function normalizeBirthdayImageKey($filename)
{
    $filename = pathinfo($filename, PATHINFO_FILENAME);

    $filename = strtolower(trim($filename));

    $filename = preg_replace('/[^a-z0-9]+/i', '_', $filename);

    return trim($filename, '_');
}

/*
|--------------------------------------------------------------------------
| CSV EXPORT
|--------------------------------------------------------------------------
*/

if (isset($_GET['export_csv'])) {

    // Remove all HTML already generated by header.php.
    ob_end_clean();

    $filename = 'birthday_students_' . date('Y-m-d_H-i-s') . '.csv';

    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Pragma: no-cache');
    header('Expires: 0');

    $output = fopen('php://output', 'w');

    // UTF-8 BOM for Excel compatibility.
    fwrite($output, "\xEF\xBB\xBF");

    /*
    |--------------------------------------------------------------------------
    | CSV HEADER
    |--------------------------------------------------------------------------
    */

    fputcsv($output, [
        'student_name',
        'class',
        'birthday',
        'image',
        'template',
        'status'
    ]);

    $exportStmt = $pdo->prepare("
        SELECT
            s.name AS student_name,
            s.class_name AS class,
            s.birthday_date AS birthday,
            s.student_image AS image,
            'Default Birthday Card' AS template,
            'Active' AS status
        FROM tbl_birthday_student s
        LEFT JOIN tbl_birthday_template t
            ON t.id = s.template_id
        ORDER BY
            s.sort_order ASC,
            s.id DESC
    ");

    $exportStmt->execute();

    while ($exportRow = $exportStmt->fetch(PDO::FETCH_ASSOC)) {

        fputcsv($output, [
            $exportRow['student_name'],
            $exportRow['class'],
            $exportRow['birthday'],
            $exportRow['image'],
            $exportRow['template'],
            $exportRow['status']
        ]);
    }

    fclose($output);

    exit;
}

/*
|--------------------------------------------------------------------------
| CSV UPLOAD
|--------------------------------------------------------------------------
*/

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['upload_csv'])) {

    if (
        !isset($_FILES['birthday_csv']) ||
        $_FILES['birthday_csv']['error'] !== UPLOAD_ERR_OK
    ) {

        $error_message = 'Please select a valid CSV file.';

    } else {

        $file = $_FILES['birthday_csv'];

        /*
        |--------------------------------------------------------------------------
        | Check CSV Extension
        |--------------------------------------------------------------------------
        */

        $extension = strtolower(
            pathinfo($file['name'], PATHINFO_EXTENSION)
        );

        if ($extension !== 'csv') {

            $error_message = 'Only CSV files are allowed.';

        } else {

            $handle = fopen($file['tmp_name'], 'r');

            if ($handle === false) {

                $error_message = 'Unable to read the CSV file.';

            } else {

                /*
                |--------------------------------------------------------------------------
                | Find Default Birthday Card Template
                |--------------------------------------------------------------------------
                */

                $templateStmt = $pdo->prepare("
                    SELECT id
                    FROM tbl_birthday_template
                    WHERE LOWER(TRIM(title)) = LOWER(TRIM(?))
                    LIMIT 1
                ");

                $templateStmt->execute([
                    'Default Birthday Card'
                ]);

                $defaultTemplate = $templateStmt->fetch(PDO::FETCH_ASSOC);

                if (!$defaultTemplate) {

                    fclose($handle);

                    $error_message =
                        'Default Birthday Card template was not found. Please create the template first.';

                } else {

                    $templateId = (int)$defaultTemplate['id'];

                    /*
                    |--------------------------------------------------------------------------
                    | Read CSV Header
                    |--------------------------------------------------------------------------
                    */

                    $header = fgetcsv($handle);

                    if (!$header) {

                        fclose($handle);

                        $error_message = 'The CSV file is empty.';

                    } else {

                        /*
                        |--------------------------------------------------------------------------
                        | Remove UTF-8 BOM
                        |--------------------------------------------------------------------------
                        */

                        $header[0] = preg_replace(
                            '/^\xEF\xBB\xBF/',
                            '',
                            $header[0]
                        );

                        /*
                        |--------------------------------------------------------------------------
                        | Normalize Header Names
                        |--------------------------------------------------------------------------
                        */

                        $header = array_map(function ($value) {

                            return strtolower(trim($value));

                        }, $header);

                        /*
                        |--------------------------------------------------------------------------
                        | Required Columns
                        |--------------------------------------------------------------------------
                        |
                        | IMAGE IS NOT REQUIRED.
                        |
                        | PHP automatically creates:
                        |
                        | Rumi + 5 = rumi_5.jpg
                        |
                        */

                        $requiredColumns = [
                            'student_name',
                            'class',
                            'birthday',
                            'template',
                            'status'
                        ];

                        $missingColumns = [];

                        foreach ($requiredColumns as $column) {

                            if (!in_array($column, $header, true)) {

                                $missingColumns[] = $column;
                            }
                        }

                        if (!empty($missingColumns)) {

                            fclose($handle);

                            $error_message =
                                'Missing CSV column(s): ' .
                                implode(', ', $missingColumns);

                        } else {

                            /*
                            |--------------------------------------------------------------------------
                            | Get Column Positions
                            |--------------------------------------------------------------------------
                            */

                            $studentNameIndex =
                                array_search(
                                    'student_name',
                                    $header,
                                    true
                                );

                            $classIndex =
                                array_search(
                                    'class',
                                    $header,
                                    true
                                );

                            $birthdayIndex =
                                array_search(
                                    'birthday',
                                    $header,
                                    true
                                );

                            $templateIndex =
                                array_search(
                                    'template',
                                    $header,
                                    true
                                );

                            $statusIndex =
                                array_search(
                                    'status',
                                    $header,
                                    true
                                );

                            // The image column is optional for older CSV files.
                            $imageIndex = array_search('image', $header, true);
                            if ($imageIndex === false) {
                                $imageIndex = array_search('student_image', $header, true);
                            }

                            $imported = 0;
                            $updated = 0;
                            $failed = 0;

                            $errors = [];

                            $rowNumber = 1;

                            try {

                                $pdo->beginTransaction();

                                /*
                                |--------------------------------------------------------------------------
                                | Find Existing Student By Name And Class
                                |--------------------------------------------------------------------------
                                */

                                $findByClassStmt = $pdo->prepare("
                                    SELECT id
                                    FROM tbl_birthday_student
                                                                        WHERE LOWER(TRIM(name)) = LOWER(TRIM(?))
                                                                            AND LOWER(TRIM(class_name)) = LOWER(TRIM(?))
                                    ORDER BY id ASC
                                    LIMIT 1
                                ");

                                /*
                                |--------------------------------------------------------------------------
                                | INSERT
                                |--------------------------------------------------------------------------
                                */

                                $insertStmt = $pdo->prepare("
                                    INSERT INTO tbl_birthday_student
                                    (
                                        name,
                                        class_name,
                                        birthday_date,
                                        student_image,
                                        template_id,
                                        status
                                    )
                                    VALUES
                                    (
                                        ?,
                                        ?,
                                        ?,
                                        ?,
                                        ?,
                                        ?
                                    )
                                ");

                                /*
                                |--------------------------------------------------------------------------
                                | UPDATE
                                |--------------------------------------------------------------------------
                                */

                                $updateStmt = $pdo->prepare("
                                    UPDATE tbl_birthday_student
                                    SET
                                        name = ?,
                                        class_name = ?,
                                        birthday_date = ?,
                                        student_image = ?,
                                        template_id = ?,
                                        status = ?
                                    WHERE id = ?
                                ");

                                /*
                                |--------------------------------------------------------------------------
                                | Read CSV Rows
                                |--------------------------------------------------------------------------
                                */

                                while (($data = fgetcsv($handle)) !== false) {

                                    $rowNumber++;

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Skip Empty Rows
                                    |--------------------------------------------------------------------------
                                    */

                                    if (
                                        count($data) === 1 &&
                                        trim($data[0]) === ''
                                    ) {

                                        continue;
                                    }

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Get Values
                                    |--------------------------------------------------------------------------
                                    */

                                    $studentName =
                                        trim(
                                            $data[$studentNameIndex] ?? ''
                                        );

                                    $className =
                                        trim(
                                            $data[$classIndex] ?? ''
                                        );

                                    $birthday =
                                        trim(
                                            $data[$birthdayIndex] ?? ''
                                        );

                                    $template =
                                        trim(
                                            $data[$templateIndex] ?? ''
                                        );

                                    $status =
                                        trim(
                                            $data[$statusIndex] ?? ''
                                        );

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Generate Student Image Filename
                                    |--------------------------------------------------------------------------
                                    |
                                    | Rumi + 5
                                    |
                                    | becomes:
                                    |
                                    | rumi_5.jpg
                                    |
                                    */

                                    // Keep the CSV image extension when valid, but always
                                    // use the predictable name_class filename.
                                    $csvImage = $imageIndex !== false
                                        ? basename(trim($data[$imageIndex] ?? ''))
                                        : '';
                                    $imageExtension = strtolower(
                                        pathinfo($csvImage, PATHINFO_EXTENSION)
                                    );
                                    if (!in_array($imageExtension, ['jpg', 'jpeg', 'png', 'gif', 'webp'], true)) {
                                        $imageExtension = 'jpg';
                                    }
                                    $studentImage = createBirthdayImageName(
                                        $studentName,
                                        $className,
                                        $imageExtension
                                    );

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Validate Student Name
                                    |--------------------------------------------------------------------------
                                    */

                                    if ($studentName === '') {

                                        $failed++;

                                        $errors[] =
                                            "Row {$rowNumber}: Student name is required.";

                                        continue;
                                    }

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Validate Class
                                    |--------------------------------------------------------------------------
                                    */

                                    if ($className === '') {

                                        $failed++;

                                        $errors[] =
                                            "Row {$rowNumber}: Class is required.";

                                        continue;
                                    }

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Validate Birthday
                                    |--------------------------------------------------------------------------
                                    */

                                    if ($birthday !== '') {

                                        $dateObject =
                                            DateTime::createFromFormat(
                                                'Y-m-d',
                                                $birthday
                                            );

                                        if (
                                            !$dateObject ||
                                            $dateObject->format('Y-m-d') !== $birthday
                                        ) {

                                            $failed++;

                                            $errors[] =
                                                "Row {$rowNumber}: Invalid birthday '{$birthday}'. Use YYYY-MM-DD.";

                                            continue;
                                        }
                                    }

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Template MUST be Default Birthday Card
                                    |--------------------------------------------------------------------------
                                    */

                                    if (
                                        strcasecmp(
                                            $template,
                                            'Default Birthday Card'
                                        ) !== 0
                                    ) {

                                        $failed++;

                                        $errors[] =
                                            "Row {$rowNumber}: Template must be 'Default Birthday Card'.";

                                        continue;
                                    }

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Status MUST be Active
                                    |--------------------------------------------------------------------------
                                    */

                                    if (
                                        strcasecmp(
                                            $status,
                                            'Active'
                                        ) !== 0
                                    ) {

                                        $failed++;

                                        $errors[] =
                                            "Row {$rowNumber}: Status must be 'Active'.";

                                        continue;
                                    }

                                    /*
                                    |--------------------------------------------------------------------------
                                    | Find Existing Student
                                    |--------------------------------------------------------------------------
                                    */

                                    $findByClassStmt->execute([
                                        $studentName,
                                        $className
                                    ]);

                                    $existingStudent =
                                        $findByClassStmt->fetch(
                                            PDO::FETCH_ASSOC
                                        );

                                    /*
                                    |--------------------------------------------------------------------------
                                    | UPDATE EXISTING
                                    |--------------------------------------------------------------------------
                                    */

                                    if ($existingStudent) {

                                        $updateStmt->execute([
                                            $studentName,
                                            $className,
                                            $birthday,
                                            $studentImage,
                                            $templateId,
                                            'Active',
                                            (int)$existingStudent['id']
                                        ]);

                                        $updated++;

                                    } else {

                                        /*
                                        |--------------------------------------------------------------------------
                                        | INSERT NEW
                                        |--------------------------------------------------------------------------
                                        */

                                        $insertStmt->execute([
                                            $studentName,
                                            $className,
                                            $birthday,
                                            $studentImage,
                                            $templateId,
                                            'Active'
                                        ]);

                                        $imported++;
                                    }
                                }

                                fclose($handle);

                                $pdo->commit();

                                /*
                                |--------------------------------------------------------------------------
                                | Success Message
                                |--------------------------------------------------------------------------
                                */

                                if ($imported > 0 || $updated > 0) {

                                    $messageParts = [];

                                    if ($imported > 0) {

                                        $messageParts[] =
                                            "{$imported} birthday student(s) added";
                                    }

                                    if ($updated > 0) {

                                        $messageParts[] =
                                            "{$updated} birthday student(s) updated";
                                    }

                                    $success_message =
                                        implode('. ', $messageParts) . '.';

                                    if ($failed > 0) {

                                        $success_message .=
                                            " {$failed} row(s) were skipped.";
                                    }

                                } else {

                                    $error_message =
                                        'No students were imported or updated.';

                                    if (!empty($errors)) {

                                        $error_message .=
                                            ' Please check the errors below.';
                                    }
                                }

                            } catch (Exception $e) {

                                if ($pdo->inTransaction()) {

                                    $pdo->rollBack();
                                }

                                fclose($handle);

                                $error_message =
                                    'CSV import failed: ' .
                                    $e->getMessage();
                            }

                            /*
                            |--------------------------------------------------------------------------
                            | Display Row Errors
                            |--------------------------------------------------------------------------
                            */

                            if (!empty($errors)) {

                                $error_message .=
                                    '<br><br><strong>Import Errors:</strong><br>';

                                $error_message .=
                                    implode(
                                        '<br>',
                                        array_map(
                                            'htmlspecialchars',
                                            $errors
                                        )
                                    );
                            }
                        }
                    }
                }
            }
        }
    }
}

/*
|--------------------------------------------------------------------------
| BULK IMAGE UPLOAD
|--------------------------------------------------------------------------
|
| Select multiple images at once.
|
| Example:
|
| rumi_5.jpg
| sita_6.jpg
| ram_7.jpg
|
| The system finds the matching student and updates student_image.
|
*/

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['upload_images'])) {

    if (
        !isset($_FILES['birthday_images']) ||
        !isset($_FILES['birthday_images']['name']) ||
        !is_array($_FILES['birthday_images']['name'])
    ) {

        $error_message = 'Please select one or more image files.';

    } else {

        $uploadedCount = 0;
        $updatedCount = 0;
        $skippedCount = 0;

        $imageErrors = [];

        /*
        |--------------------------------------------------------------------------
        | Allowed Image Types
        |--------------------------------------------------------------------------
        */

        $allowedExtensions = [
            'jpg',
            'jpeg',
            'gif',
            'png',
            'webp'
        ];

        /*
        |--------------------------------------------------------------------------
        | Prepare Student Records
        |--------------------------------------------------------------------------
        */

        $studentStmt = $pdo->prepare("
            SELECT
                id,
                name,
                class_name
            FROM tbl_birthday_student
        ");

        $studentStmt->execute();

        $students = $studentStmt->fetchAll(PDO::FETCH_ASSOC);

        /*
        |--------------------------------------------------------------------------
        | Build Student Lookup
        |--------------------------------------------------------------------------
        |
        | Example:
        |
        | Rumi + 5
        |
        | becomes:
        |
        | rumi_5
        |
        */

        $studentLookup = [];

        foreach ($students as $student) {

            $expectedFilename =
                createBirthdayImageName(
                    $student['name'],
                    $student['class_name']
                );

            $lookupKey =
                normalizeBirthdayImageKey(
                    $expectedFilename
                );

            $studentLookup[$lookupKey] = [
                'id' => (int)$student['id'],
                'name' => $student['name'],
                'class_name' => $student['class_name'],
                'filename' => $expectedFilename
            ];
        }

        /*
        |--------------------------------------------------------------------------
        | Process Every Selected Image
        |--------------------------------------------------------------------------
        */

        $totalImages =
            count($_FILES['birthday_images']['name']);

        for ($i = 0; $i < $totalImages; $i++) {

            $originalName =
                $_FILES['birthday_images']['name'][$i];

            $tmpName =
                $_FILES['birthday_images']['tmp_name'][$i];

            $uploadError =
                $_FILES['birthday_images']['error'][$i];

            /*
            |--------------------------------------------------------------------------
            | Check Upload Error
            |--------------------------------------------------------------------------
            */

            if ($uploadError !== UPLOAD_ERR_OK) {

                $skippedCount++;

                $imageErrors[] =
                    "Image '{$originalName}' could not be uploaded.";

                continue;
            }

            /*
            |--------------------------------------------------------------------------
            | Check Extension
            |--------------------------------------------------------------------------
            */

            $extension =
                strtolower(
                    pathinfo(
                        $originalName,
                        PATHINFO_EXTENSION
                    )
                );

            if (!in_array($extension, $allowedExtensions, true)) {

                $skippedCount++;

                $imageErrors[] =
                    "Image '{$originalName}' is not a supported image.";

                continue;
            }

            /*
            |--------------------------------------------------------------------------
            | Verify Actual Image
            |--------------------------------------------------------------------------
            */

            $imageInfo = @getimagesize($tmpName);

            if ($imageInfo === false) {

                $skippedCount++;

                $imageErrors[] =
                    "Image '{$originalName}' is not a valid image.";

                continue;
            }

            /*
            |--------------------------------------------------------------------------
            | Find Student By Filename
            |--------------------------------------------------------------------------
            |
            | rumi_5.jpg
            |
            | becomes:
            |
            | rumi_5
            |
            */

            $imageKey =
                normalizeBirthdayImageKey(
                    $originalName
                );

            if (!isset($studentLookup[$imageKey])) {

                $skippedCount++;

                $imageErrors[] =
                    "Image '{$originalName}' does not match any student. Expected filename format: studentname_class.jpg";

                continue;
            }

            $student =
                $studentLookup[$imageKey];

            /*
            |--------------------------------------------------------------------------
            | Always Save With Standard Filename
            |--------------------------------------------------------------------------
            |
            | Even if user uploads:
            |
            | RUMI_5.JPG
            |
            | it will be saved as:
            |
            | rumi_5.jpg
            |
            */

            $destinationFilename =
                createBirthdayImageName(
                    $student['name'],
                    $student['class_name'],
                    $extension
                );

            /*
            |--------------------------------------------------------------------------
            | Destination Path
            |--------------------------------------------------------------------------
            */

            $destinationPath =
                adminUploadsPath(
                    $destinationFilename
                );

            $destinationDirectory =
                dirname($destinationPath);

            /*
            |--------------------------------------------------------------------------
            | Create Directory If Needed
            |--------------------------------------------------------------------------
            */

            if (!is_dir($destinationDirectory)) {

                if (
                    !mkdir(
                        $destinationDirectory,
                        0755,
                        true
                    )
                ) {

                    $skippedCount++;

                    $imageErrors[] =
                        "Unable to create upload directory for '{$originalName}'.";

                    continue;
                }
            }

            /*
            |--------------------------------------------------------------------------
            | Move Image
            |--------------------------------------------------------------------------
            */

            if (
                !move_uploaded_file(
                    $tmpName,
                    $destinationPath
                )
            ) {

                $skippedCount++;

                $imageErrors[] =
                    "Unable to save image '{$originalName}'.";

                continue;
            }

            /*
            |--------------------------------------------------------------------------
            | Update Database
            |--------------------------------------------------------------------------
            */

            try {

                $imageUpdateStmt = $pdo->prepare("
                    UPDATE tbl_birthday_student
                    SET student_image = ?
                    WHERE id = ?
                ");

                $imageUpdateStmt->execute([
                    $destinationFilename,
                    $student['id']
                ]);

                $updatedCount++;
                $uploadedCount++;

            } catch (Exception $e) {

                /*
                |--------------------------------------------------------------------------
                | Remove Uploaded File If Database Update Fails
                |--------------------------------------------------------------------------
                */

                if (is_file($destinationPath)) {

                    @unlink($destinationPath);
                }

                $skippedCount++;

                $imageErrors[] =
                    "Database update failed for '{$originalName}': " .
                    $e->getMessage();
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Bulk Image Upload Message
        |--------------------------------------------------------------------------
        */

        if ($updatedCount > 0) {

            $success_message =
                "{$updatedCount} student image(s) uploaded and matched successfully.";

            if ($skippedCount > 0) {

                $success_message .=
                    " {$skippedCount} image(s) were skipped.";
            }

        } else {

            $error_message =
                'No student images were uploaded.';

            if (!empty($imageErrors)) {

                $error_message .=
                    '<br><br><strong>Image Upload Errors:</strong><br>' .
                    implode(
                        '<br>',
                        array_map(
                            'htmlspecialchars',
                            $imageErrors
                        )
                    );
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Display Image Errors Even When Some Images Succeeded
        |--------------------------------------------------------------------------
        */

        if (
            $updatedCount > 0 &&
            !empty($imageErrors)
        ) {

            $error_message =
                '<strong>Skipped Images:</strong><br>' .
                implode(
                    '<br>',
                    array_map(
                        'htmlspecialchars',
                        $imageErrors
                    )
                );
        }
    }
}

/*
|--------------------------------------------------------------------------
| Success / Delete Messages
|--------------------------------------------------------------------------
*/

if (isset($_GET['success'])) {

    $success_message =
        'Birthday student is added successfully!';

} elseif (isset($_GET['updated'])) {

    $success_message =
        'Birthday student is updated successfully!';

} elseif (isset($_GET['deleted'])) {

    $success_message =
        'Birthday student is deleted successfully!';
}

?>

<section class="content-header">

    <div class="content-header-left">

        <h1>Birthday Students</h1>

    </div>

    <div class="content-header-right">

        <!-- CSV Export -->
        <a
            href="?export_csv=1"
            class="btn btn-info btn-sm"
        >
            <i class="fa fa-download"></i>
            Export CSV
        </a>

        <!-- CSV Upload -->
        <button
            type="button"
            class="btn btn-success btn-sm"
            data-toggle="modal"
            data-target="#csvUploadModal"
        >
            <i class="fa fa-upload"></i>
            Upload CSV
        </button>

        <!-- Bulk Image Upload -->
        <button
            type="button"
            class="btn btn-warning btn-sm"
            data-toggle="modal"
            data-target="#imageUploadModal"
        >
            <i class="fa fa-picture-o"></i>
            Upload Images
        </button>

        <!-- Add Student -->
        <a
            href="birthday-add.php"
            class="btn btn-primary btn-sm"
        >
            Add Student
        </a>

    </div>

</section>


<section class="content">

    <div class="row">

        <div class="col-md-12">

            <?php if ($error_message): ?>

                <div class="callout callout-danger">

                    <p>
                        <?php echo $error_message; ?>
                    </p>

                </div>

            <?php endif; ?>


            <?php if ($success_message): ?>

                <div class="callout callout-success">

                    <p>
                        <?php echo htmlspecialchars($success_message); ?>
                    </p>

                </div>

            <?php endif; ?>


            <div class="box box-info">

                <div class="box-body table-responsive">

                    <table
                        id="example1"
                        class="table table-bordered table-hover table-striped"
                    >

                        <thead>

                            <tr>

                                <th width="30">
                                    #
                                </th>

                                <th width="80">
                                    Student Photo
                                </th>

                                <th>
                                    Name
                                </th>

                                <th>
                                    Class
                                </th>

                                <th>
                                    Birthday
                                </th>

                                <th>
                                    Template
                                </th>

                                <th>
                                    Status
                                </th>

                                <th width="210">
                                    Action
                                </th>

                            </tr>

                        </thead>


                        <tbody>

                            <?php

                            $i = 0;

                            $statement = $pdo->prepare("
                                SELECT
                                    s.*,
                                    t.title AS template_title
                                FROM tbl_birthday_student s
                                LEFT JOIN tbl_birthday_template t
                                    ON t.id = s.template_id
                                ORDER BY
                                    s.sort_order ASC,
                                    s.id DESC
                            ");

                            $statement->execute();

                            foreach (
                                $statement->fetchAll(PDO::FETCH_ASSOC)
                                as $row
                            ) {

                                $i++;

                            ?>

                                <tr>

                                    <td>
                                        <?php echo $i; ?>
                                    </td>


                                    <td>

                                        <?php if (
                                            !empty($row['student_image']) &&
                                            is_file(
                                                adminUploadsPath(
                                                    $row['student_image']
                                                )
                                            )
                                        ): ?>

                                            <img
                                                src="<?php echo htmlspecialchars(
                                                    adminUploadUrl(
                                                        $row['student_image']
                                                    )
                                                ); ?>"
                                                style="
                                                    width:58px;
                                                    height:66px;
                                                    object-fit:cover;
                                                    background:#f2f2f2;
                                                    padding:4px;
                                                "
                                            >

                                        <?php else: ?>

                                            <span class="text-muted">
                                                Missing
                                            </span>

                                        <?php endif; ?>

                                    </td>


                                    <td>
                                        <?php echo htmlspecialchars(
                                            $row['name']
                                        ); ?>
                                    </td>


                                    <td>
                                        <?php echo htmlspecialchars(
                                            $row['class_name']
                                        ); ?>
                                    </td>


                                    <td>
                                        <?php echo htmlspecialchars(
                                            $row['birthday_date']
                                        ); ?>
                                    </td>


                                    <td>
                                        <?php echo htmlspecialchars(
                                            $row['template_title'] ?? ''
                                        ); ?>
                                    </td>


                                    <td>
                                        <?php echo htmlspecialchars(
                                            $row['status']
                                        ); ?>
                                    </td>


                                    <td>

                                        <a
                                            href="birthday-edit.php?id=<?php echo (int)$row['id']; ?>"
                                            class="btn btn-primary btn-xs"
                                        >
                                            Edit
                                        </a>


                                        <a
                                            href="birthday-generate.php?id=<?php echo (int)$row['id']; ?>"
                                            class="btn btn-success btn-xs"
                                        >
                                            Generate
                                        </a>


                                        <?php if (
                                            !empty($row['generated_image'])
                                        ): ?>

                                            <a
                                                href="birthday-download.php?id=<?php echo (int)$row['id']; ?>"
                                                class="btn btn-info btn-xs"
                                            >
                                                Download
                                            </a>

                                        <?php endif; ?>


                                        <a
                                            href="#"
                                            class="btn btn-danger btn-xs"
                                            data-href="birthday-delete.php?id=<?php echo (int)$row['id']; ?>"
                                            data-toggle="modal"
                                            data-target="#confirm-delete"
                                        >
                                            Delete
                                        </a>

                                    </td>

                                </tr>

                            <?php } ?>

                        </tbody>

                    </table>

                </div>

            </div>

        </div>

    </div>

</section>


<!--
|--------------------------------------------------------------------------
| CSV UPLOAD MODAL
|--------------------------------------------------------------------------
-->

<div
    class="modal fade"
    id="csvUploadModal"
    tabindex="-1"
    role="dialog"
    aria-hidden="true"
>

    <div class="modal-dialog">

        <div class="modal-content">

            <form
                method="post"
                enctype="multipart/form-data"
            >

                <div class="modal-header">

                    <button
                        type="button"
                        class="close"
                        data-dismiss="modal"
                    >
                        &times;
                    </button>

                    <h4 class="modal-title">
                        Upload Birthday Students CSV
                    </h4>

                </div>


                <div class="modal-body">

                    <div class="alert alert-info">

                        <strong>CSV Format:</strong>

                        <br><br>

                        Required CSV columns:

                        <br>

                        <code>
                            student_name,class,birthday,template,status
                        </code>

                        <br>

                        Optional image column: <code>image</code> or <code>student_image</code>.

                        <br><br>

                        <strong>Example:</strong>

                        <br>

                        <code>
                            student_name,class,birthday,image,template,status
                        </code>

                        <br>

                        <code>
                            Rumi,5,2012-08-15,rumi_5.jpg,Default Birthday Card,Active
                        </code>

                        <br>

                        <code>
                            Sita,6,2011-09-20,sita_6.jpg,Default Birthday Card,Active
                        </code>

                        <br><br>

                        <strong>Image filename is generated automatically.</strong>

                        <br>

                        <code>
                            Rumi + 5 = rumi_5.jpg
                        </code>

                        <br>

                        <code>
                            Sita + 6 = sita_6.jpg
                        </code>

                        <br><br>

                        <strong>Important:</strong>

                        <ul style="padding-left:20px;margin-bottom:0;">

                            <li>
                                When provided, birthday format must be
                                <strong>YYYY-MM-DD</strong>
                            </li>

                            <li>
                                Template must be
                                <strong>Default Birthday Card</strong>
                            </li>

                            <li>
                                Status must be
                                <strong>Active</strong>
                            </li>

                            <li>
                                Student image is generated automatically from
                                student name and class. The image column is optional;
                                if provided, its supported extension is retained.
                            </li>

                            <li>
                                Upload actual images separately using
                                <strong>Upload Images</strong>.
                            </li>

                            <li>
                                If the student name and class already exist,
                                that birthday student record will be updated.
                            </li>

                            <li>
                                If the student name and class do not exist,
                                a new birthday student record will be added.
                            </li>

                        </ul>

                    </div>


                    <div class="form-group">

                        <label>
                            Select CSV File
                        </label>

                        <input
                            type="file"
                            name="birthday_csv"
                            class="form-control"
                            accept=".csv"
                            required
                        >

                    </div>

                </div>


                <div class="modal-footer">

                    <button
                        type="button"
                        class="btn btn-default"
                        data-dismiss="modal"
                    >
                        Cancel
                    </button>

                    <button
                        type="submit"
                        name="upload_csv"
                        value="1"
                        class="btn btn-success"
                    >

                        <i class="fa fa-upload"></i>

                        Upload CSV

                    </button>

                </div>

            </form>

        </div>

    </div>

</div>


<!--
|--------------------------------------------------------------------------
| BULK IMAGE UPLOAD MODAL
|--------------------------------------------------------------------------
-->

<div
    class="modal fade"
    id="imageUploadModal"
    tabindex="-1"
    role="dialog"
    aria-hidden="true"
>

    <div class="modal-dialog">

        <div class="modal-content">

            <form
                method="post"
                enctype="multipart/form-data"
            >

                <div class="modal-header">

                    <button
                        type="button"
                        class="close"
                        data-dismiss="modal"
                    >
                        &times;
                    </button>

                    <h4 class="modal-title">
                        Upload Student Images
                    </h4>

                </div>


                <div class="modal-body">

                    <div class="alert alert-warning">

                        <strong>Image Filename Rule</strong>

                        <br><br>

                        Image filename must be:

                        <br>

                        <code>
                            studentname_class.jpg
                        </code>

                        <br><br>

                        Example:

                        <br>

                        <code>
                            rumi_5.jpg
                        </code>

                        <br>

                        <code>
                            sita_6.jpg
                        </code>

                        <br>

                        <code>
                            ram_7.jpg
                        </code>

                        <br><br>

                        You can select multiple images at once.

                        <br>

                        JPG, JPEG, PNG, GIF and WEBP are supported.

                    </div>


                    <div class="form-group">

                        <label>
                            Select Student Images
                        </label>

                        <input
                            type="file"
                            name="birthday_images[]"
                            class="form-control"
                            accept=".jpg,.jpeg,.png,.gif,.webp,image/jpeg,image/png,image/gif,image/webp"
                            multiple
                            required
                        >

                        <p class="help-block">
                            Hold Ctrl and select multiple images, or select
                            a complete folder's images.
                        </p>

                    </div>

                </div>


                <div class="modal-footer">

                    <button
                        type="button"
                        class="btn btn-default"
                        data-dismiss="modal"
                    >
                        Cancel
                    </button>

                    <button
                        type="submit"
                        name="upload_images"
                        value="1"
                        class="btn btn-warning"
                    >

                        <i class="fa fa-picture-o"></i>

                        Upload Images

                    </button>

                </div>

            </form>

        </div>

    </div>

</div>


<!--
|--------------------------------------------------------------------------
| DELETE MODAL
|--------------------------------------------------------------------------
-->

<div
    class="modal fade"
    id="confirm-delete"
    tabindex="-1"
    role="dialog"
    aria-hidden="true"
>

    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">

                <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                >
                    &times;
                </button>

                <h4 class="modal-title">
                    Delete Confirmation
                </h4>

            </div>


            <div class="modal-body">

                <p>
                    Are you sure want to delete this birthday student?
                </p>

            </div>


            <div class="modal-footer">

                <button
                    type="button"
                    class="btn btn-default"
                    data-dismiss="modal"
                >
                    Cancel
                </button>

                <a
                    class="btn btn-danger btn-ok"
                >
                    Delete
                </a>

            </div>

        </div>

    </div>

</div>


<?php require_once('footer.php'); ?>
