-- Add invoice/order summary columns to tbl_payment if they do not already exist
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS subtotal DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS discount_type VARCHAR(20) DEFAULT 'percent';
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS discount_value DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS vat_percent DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS vat_amount DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS grand_total DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS due_amount DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS notes TEXT NULL;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS created_at DATETIME NULL;
ALTER TABLE tbl_payment ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL;

ALTER TABLE tbl_order ADD COLUMN IF NOT EXISTS line_total DECIMAL(10,2) DEFAULT 0.00;

